// web/src/App.svelte
<script lang="ts">
  import { Route, router } from 'tinro';
  import Resource from './pages/resource/Resource.svelte';
  import Root from './pages/root/Root.svelte';
  import { useNuiEvent } from './utils/useNuiEvent';
  import { resources, generalData } from './store';
  import { debugData } from './utils/debugData';

  interface OpenData {
    resources: string[];
    totalQueries: number;
    slowQueries: number;
    totalTime: number;
    chartData: {
      x: number;
      y: number;
      z: number;
    };
  }

  router.mode.hash();
  router.goto('/');

  useNuiEvent('openUI', (data: OpenData) => {
    $resources = data.resources;
    $generalData = {
      queries: data.totalQueries,
      slowQueries: data.slowQueries,
      timeQuerying: data.totalTime,
    };
  });

  debugData<OpenData>([
    {
      action: 'openUI',
      data: {
        resources: ['ox_core', 'oxmysql', 'ox_inventory', 'ox_doorlock', 'ox_lib', 'ox_vehicleshop', 'ox_target'],
        slowQueries: 13,
        totalQueries: 332,
        totalTime: 230123,
        chartData: {
          x: 2,
          y: 5,
          z: 3,
        },
      },
    },
  ]);
</script>

<main class="w-full h-full flex justify-center items-center font-main">
  <div class="bg-dark-800 text-white w-[1000px] h-[600px] flex rounded-md">
    <Route path="/">
      <Root />
    </Route>
    <Route path="/:resource">
      <Resource />
    </Route>
  </div>
</main>

// ui/src/components/App.tsx
import { Flex, Box } from '@chakra-ui/react';
import { debugData } from '../utils/debugData';
import TopBar from './NavBars/TopBar';
import LeftBar from './NavBars/LeftBar';
import { Routes, Route, useNavigate } from 'react-router-dom';
import Resource from './Resource';
import RightBar from './NavBars/RightBar';
import MainContent from './MainContent';
import { useNuiEvent } from '../hooks/useNuiEvent';

debugData([
  {
    action: 'openUI',
    data: {
      resources: ['ox_inventory', 'luke_garages', 'es_extended'],
      totalQueries: 732,
      totalTime: 258,
      slowQueries: 6,
      chartData: [
        { x: 13, y: 350, z: 'ox_inventory' },
        { x: 27, y: 752, z: 'es_extended' },
        { x: 41, y: 52, z: 'luke_garages' },
      ],
    },
  },
]);

const App: React.FC = () => {
  const navigate = useNavigate();

  useNuiEvent('openUI', () => navigate('/'));

  return (
    <Flex w="100%" h="100%" alignItems="center" justifyContent="center">
      <Box
        width="6xl"
        height="lg"
        backgroundColor="#191E26"
        borderRadius="lg"
        color="white"
        fontFamily="Poppins"
        userSelect="none"
      >
        <TopBar />
        <LeftBar />
        <RightBar />
        <MainContent>
          <Routes>
            <Route path="/:resource" element={<Resource />} />
            <Route path="/" element={<></>} />
          </Routes>
        </MainContent>
      </Box>
    </Flex>
  );
};

export default App;
